Fix logging formatting
hubblestack/hubble pull request #1138
Opened 2022-07-08 09:03 UTC by vladmonea

Formatting in MinionError references a a field 3, which should be a field 2.  May cause an exception if executed.

Note: the change-set is quite big due to linter requirements. The actual change is on line 691. Additionally, I've removed unused arguments on lines 44 and 260, respectively.

2022-07-27 15:14 UTC, grogsaxle requested changes
@vladmonea Nice cleanup.   Couple of places to tweak on log.debug() and then will be good to go.

2022-07-27 15:14 UTC, grogsaxle commented on hubblestack/fileclient.py
> +                            "Cached copy of %s (%s) matches source_hash %s, " "skipping download",
Unnecessary " " in log.debug() between %s, and skipping
`"Cached copy of %s (%s) matches source_hash %s, skipping download",`

2022-07-27 15:14 UTC, grogsaxle commented on hubblestack/fileclient.py
> +            log.debug("In saltenv '%s', looking at rel_path '%s' to resolve " "'%s'", saltenv, rel_path, path)
Unecessary " " in middle og log.debug.   Maybe change to:
`log.debug("In saltenv '%s', looking at rel_path '%s' to resolve '%s'", saltenv, rel_path, path)

2022-07-27 15:14 UTC, grogsaxle commented on hubblestack/fileclient.py
> +        log.debug("In saltenv '%s', ** considering ** path '%s' to resolve " "'%s'", saltenv, dest2check, path)
Unnecessary " " in middle of log.debug.  Maybe change to: 
`log.debug("In saltenv '%s', ** considering ** path '%s' to resolve '%s'", saltenv, dest2check, path)`

2022-08-04 13:58 UTC, mzainea approved these changes

2022-08-09 13:28 UTC, merged