Nova rewrite changes
hubblestack/hubble pull request #936
Opened 2020-09-28 05:21 UTC by devagupt

- Changes for Nova module rewrite

2020-09-28 13:01 UTC, jettero requested changes
I'm pretty much OK with most of these changes (they've been through committee); but could we get this rebased to develop? it's full of (unnecessary to preserve) merge commits and the parent fork point is from some seven weeks ago.

2020-09-28 13:34 UTC, devagupt commented
> I'm pretty much OK with most of these changes (they've been through committee); but could we get this rebased to develop? it's full of (unnecessary to preserve) merge commits and the parent fork point is from some seven weeks ago.

@jettero Thanks for pointing it out. I have fixed the commit history to have relevant commits only.

2020-09-28 15:33 UTC, jettero commented
Let's wait to see how the jenkins job turns out. It's pretty overloaded (I re-queued everything). But assuming it passes, I'll approve/merge later today.

2020-09-29 05:04 UTC, goravsingal commented
It's failing as the step mentioned in .pipeline is expecting a file: combined.svg. But it is not found.

2020-11-03 20:14 UTC, jettero requested changes
Please fix the history. There's a merge commit at the tail end of the commit list that's from some unknown branch.

2020-11-03 20:27 UTC, jettero requested changes
Instead of inventing a whole new module runner system, please use the module runner already built into the hubblestack.loader (well, it's still the salt loader in this branch). There's no need to re-invent the wheel on this.

2020-11-03 20:27 UTC, jettero commented on hubblestack/extmods/hubble_mods/win_reg.py
> +              HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Explorer\NoDataExecutionPrevention:
these backslashes are incorrect and will fail in python 3.7 or thereabouts.

Please add `r` to the `"""` (ie, `r"""`) or add another backslash to escape your escape. 

Python 3.6 and below can deal with this and does what you'd expect, but future pythons will not.

2020-11-03 20:27 UTC, jettero commented on hubblestack/extmods/hubble_mods/win_reg.py
> +              HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Explorer\NoDataExecutionPrevention:
In fact, this file won't load enough for me to even show the result under default warnings:

```
PYTHONPATH=. python -W default hubblestack/extmods/hubble_mods/win_reg.py 
  File "hubblestack/extmods/hubble_mods/win_reg.py", line 67
    """
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 426-427: malformed \N character escape
```

2020-11-04 03:09 UTC, devagupt commented
> Please fix the history. There's a merge commit at the tail end of the commit list that's from some unknown branch.

fixed

2020-11-06 16:52 UTC, jettero approved these changes

2020-11-06 16:53 UTC, merged