Fix daemonize
hubblestack/hubble pull request #961
Opened 2020-12-08 17:24 UTC by jettero

the old salt.utils.daemonize was itself a deprecated form of salt.utils.process.daemonize; ... so I added those methods back to hubblestack.utils.daemonize

2020-12-08 17:57 UTC, devagupt commented
The changes here looks good. I will merge this PR after verifying that build from it runs fine on a machine.

2020-12-08 17:58 UTC, devagupt reviewed
The changes here looks good. I will merge this PR after verifying that build from it runs fine on a machine.

2020-12-10 16:00 UTC, devagupt commented
The automation tests are not passing for this build. We need to fix them as well.
Test results can be accessed here:
https://hubble-cicd.corp.adobe.com/job/Hubble_Automation_jobs_stage/job/Hubble_Automation_centos7_stage/40/testReport/

2020-12-14 19:57 UTC, MoodyMudit requested changes

2020-12-16 13:51 UTC, jettero commented on hubblestack/files/hubblestack_nova/fdg.py
> +                _, fdg_run = __mods__['fdg.run'](fdg_file, starting_chained=starting_chained)
wait, this is the "old fdg" ? meaning this file should be removed? something might be pretty screwy. Or maybe I just don't understand what you mean.

2021-01-04 08:51 UTC, MoodyMudit requested changes

2021-01-04 08:51 UTC, MoodyMudit commented on hubblestack/files/hubblestack_nova/fdg.py
> +                _, fdg_run = __mods__['fdg.run'](fdg_file, starting_chained=starting_chained)
As discussed, this is the old fdg, can you please revert back this change.

2021-01-06 06:59 UTC, goravsingal approved these changes

2021-01-06 09:31 UTC, MoodyMudit approved these changes

2021-01-07 12:27 UTC, goravsingal approved these changes

2021-01-07 13:07 UTC, MoodyMudit approved these changes

2021-01-08 02:26 UTC, goravsingal approved these changes

2021-01-08 02:26 UTC, merged