Bringing back the fdg function to support fdg.fdg functionality
hubblestack/hubble pull request #965
Opened 2020-12-22 09:34 UTC by MoodyMudit

2020-12-23 14:31 UTC, jettero requested changes
We don't really have deprecation markings that we use (as far as I know).

Could we maybe add something to the description to indicate this is the /old/ fdg.fdg and the /new/ fdg.run is mean to replace it? Am I getting that totally wrong? I recall that being the tail end of the discussion.

2020-12-23 14:32 UTC, jettero commented
Er, by "description" I mean the function docs for fdg.run and/or fdg.fdg...

2021-01-05 07:02 UTC, goravsingal approved these changes

2021-01-05 15:25 UTC, jettero approved these changes

2021-01-05 15:25 UTC, merged